### ISSUE TITLE
Optionally respond with example data from Swagger spec

### ISSUE THREAD

**Issue by holic** [BigstickCarpet/swagger-server#1]
The Swagger spec allows for properties to have an `example`. It would be great if, instead of returning an empty response, a response object would be populated with the spec's `example` data.

As an aside, thanks for working on this! I've had a hell of a time trying to find a library I can use to mock a Swagger server to write integration tests for my API's JS client library.

**Comment by BigstickCarpet** [comment]
Thanks for the feedback.  I'm glad you're finding this project useful!

The Swagger spec allows for an `example` property and a `default` property.  Currently, I'm ignoring the `example` property, but I _do_ honor the `default` property.  So you can use that property to provide a default value for your response object.   You're not the first person to request this feature though, so in the next version of Swagger-Server, I will honor _both_ the `default` and the `example` properties.

**Comment by holic** [comment]
:+1: 

I don't want to pollute the spec with examples as defaults, because the examples aren't truly defaults. Furthermore, the Swagger spec in question is used by a few different languages and applications, so it needs to be a consistent view of the API, rather than tailored to one use-case.

**Comment by BigstickCarpet** [comment]
Just FYI - the new version of Swagger Server is coming along nicely. The entire middleware layer is done now, and I've released it as a separate, standalone project ([Swagger Express Middleware](https://www.npmjs.com/package/swagger-express-middleware))

The new mock middleware supports `default` and `example` values, as we discussed.

**Comment by dzdrazil** [comment]
I may be a bit late to the party, but I've recently published a mocking middleware for swagger; take a look and use, adapt or ignore as you please: https://github.com/dzdrazil/swagger-mock-api

It leverages the http://chancejs.com/ library rather than hard-coded examples in the swagger file, so it gives a bit of a more dynamic feel.

**Comment by BigstickCarpet** [comment]
@dzdrazil - Thanks for bringing that up.  I've kinda had a back-burner plan to do something like that at some point in the future.  I just [created an issue](https://github.com/BigstickCarpet/swagger-express-middleware/issues/8) for this so it doesn't get forgotten

**Comment by BigstickCarpet** [comment]
Closing this issue, since the original feature request has been implemented
