### ISSUE TITLE
Can I use this to test other language API's like Java or Scala

### ISSUE THREAD

**Issue by arnoldangel** [BigstickCarpet/swagger-server#13]
Can I use this to test other language API's like Java or Scala.

Is this for node applications only?

**Comment by BigstickCarpet** [comment]
I'm not sure I understand the question, but hopefully this helps...

Swagger Server is an HTTP server that serves REST APIs based on Swagger definitions.  Swagger Server is written in NodeJS, so, yes, Node is required on the server-side.  But the REST APIs can be accessed by _any_ client, regardless of what it's written in.  You can write your client in Java, Scala, Ruby, .Net, or any other technology that is capable of sending HTTP requests and receiving HTTP responses.

**Comment by arnoldangel** [comment]
You answered my question. I thought this was specifically for applications deployed or written for node.js only.

We use typesafe playframework.
