### ISSUE TITLE
Responding with swagger spec example data

### ISSUE THREAD

**Issue by supernik** [BigstickCarpet/swagger-server#14]
Is the swagger server able to return the example data which is included in the swagger spec rather than having to pre-populate the server?

**Comment by BigstickCarpet** [comment]
Sorry for the delayed response.  I've been away on holiday for a few weeks.

Good news! The answer to your question is, yes.  Swagger Server uses [Swagger Express Middleware](https://github.com/BigstickCarpet/swagger-express-middleware) under the hood.  Specifically, it uses the [Mock Middleware](https://github.com/BigstickCarpet/swagger-express-middleware/blob/master/docs/middleware/mock.md) to provide automatic mock implementations for your Swagger API.  The Mock Middleware supports the `default` and `example` properties in your Swagger API, [as described here](https://github.com/BigstickCarpet/swagger-express-middleware/blob/master/docs/middleware/mock.md#default-and-example-responses).

I hope that helps!  If not, then please let me know.

**Comment by supernik** [comment]
Thanks for the response. I've basically implemented just that with your swagger parser which was very simple to do but it appears also unnecessary.  I'll remove my changes and try it the easy built-in way.  Thanks!
