### ISSUE TITLE
Question: Should the samples be serving mock responses?

### ISSUE THREAD

**Issue by twalker** [BigstickCarpet/swagger-server#2]
When running the petstore example in this repo, as well as the sample the the swagger suite, I am not getting a response body from requests. 

e.g. `/api/pets` returns 

```javascript
[]
```
Is this expected, or should there be some auto-generated json models based on the schema?
I've tried v0.0.8 as well as v0.0.X with node v0.10 and node v0.12.

**Comment by BigstickCarpet** [comment]
Yeah, that's by design.  Sorry that it's so poorly documented.  I'm working on a new version right now, and it's going to be [much better documented](https://github.com/BigstickCarpet/swagger-express-middleware/blob/master/docs/samples/running.md)

The petstore sample doesn't load any mock data.  It just provides a mock _implementation_.  So when you `GET /api/pets`, you'll get back an empty array.  But if you `POST` some data to `/api/pets` and then do another `GET`, you should see the data you posted.

**Comment by twalker** [comment]
Thank you. The new documentation makes it much clearer.

Any suggestions on how to populate the implementation with some initial data?  `example` properties in the schema definitions? Or a script that posts a Postman collection? It'd be awesome if there was a module that would autogenerate seeds. Something like `spawnMocks(modelDef, howMany).

Thanks again.

**Comment by deardooley** [comment]
There is not a 100% work-free way to do that, but you can use faker.js to autogenerate test data for you. That is sufficient for most things and you can introspection your models if your types are more complex.



--
Rion

----- Reply message -----

**Comment by BigstickCarpet** [comment]
See the [sample 2 source code](https://github.com/BigstickCarpet/swagger-express-middleware/blob/master/samples/sample2.js#L22) for an example of populating initial data.   I'm sill working on the [sample 2 walkthrough](https://github.com/BigstickCarpet/swagger-express-middleware/blob/master/docs/samples/walkthrough2.md), which will explain how it works in detail.   

One really easy way to load a lot of sample data is to use the [Resource.parse()](https://github.com/BigstickCarpet/swagger-express-middleware/blob/master/docs/exports/Resource.md#parsejson) method.  You can pass it an array of JSON data, and it'll convert it all to `Resource` objects, which you can then pass to [DataStore.save()](https://github.com/BigstickCarpet/swagger-express-middleware/blob/master/docs/exports/DataStore.md#saveresource1-resource2--callback).   Here's an example:

````javascript
var data = [
    {collection: '/pets', name: '/Lassie', data: {name: 'Lassie', type: 'dog'}},
    {collection: '/pets', name: '/Clifford', data: {name: 'Clifford', type: 'dog'}},
    {collection: '/pets', name: '/Garfield', data: {name: 'Garfield', type: 'cat'}},
    {collection: '/pets', name: '/Snoopy', data: {name: 'Snoopy', type: 'dog'}},
    {collection: '/pets', name: '/Hello%20Kitty', data: {name: 'Hello Kitty', type: 'cat'}}
];

var myDB = new MemoryDataStore();
myDB.save(Resource.parse(data));
````
