### ISSUE TITLE
sample links are not working

### ISSUE THREAD

**Issue by aviadavi** [BigstickCarpet/swagger-server#3]
for example :
https://github.com/BigstickCarpet/swagger-server/tree/master/samples/petstore

Where can i see a live demo of this?

**Comment by deardooley** [comment]
I'm happy to host trunk and the latest release if the project will accept a pull request for the Dockerfile and compose file.

--
Rion

----- Reply message -----

**Comment by BigstickCarpet** [comment]
The `master` branch is where I'm doing my current development (bad practice, I know), so it's not ready to be used right now.   The [0.0.X branch](https://github.com/BigstickCarpet/swagger-server/tree/0.0.X) is the "officially released" version.  

The samples in the `master` branch aren't currently working, and they may still change significantly.  I'm still trying out different ideas to see what I want the API to be.

**Comment by BigstickCarpet** [comment]
Closing this issue, since the sample links all work now.   Sample 1 and Sample 2 are pretty solid and have complete walkthroughs.  Sample 3 is still a work in progress.
