### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by ericwooley** [BigstickCarpet/swagger-server#35]
I'm doing some research, and this looks interesting, but no updates since sepetember 2015, and version 1 is still set to alpha?

Seems like this project maybe dead? or is 1.18 alpha stable enough that no one felt the need to improve anything? If so can that be released as 1.0.0?

**Comment by BigstickCarpet** [comment]
Coincidentally, this same question was just asked a few days ago on a related project of mine. Please refer to my answer there, as the same applies to this project. 

https://github.com/BigstickCarpet/swagger-express-middleware/issues/73

**TL;DR:** I'm sorry for apparently falling off the face of the earth for the past year, and I hope to breathe new life into all of my open-source projects soon.

**Comment by ericwooley** [comment]
Great to know! So obviously you would be accepting PR's etc...? Any big refactor plans?

**Comment by BigstickCarpet** [comment]
There will definitely be some big changes to the codebase, but we're not 100% sure what it will look like.  The first step is to update all the dependent projects that make-up Swagger Server.  Once those projects are updated, we'll decide what changes make sense for Swagger Server

**Comment by Neirda24** [comment]
Hi @BigstickCarpet . Are you still planning to refactor this ? Regards.

**Comment by JamesMessinger** [comment]
I no longer have the bandwidth to maintain this project.  I have updated [the readme](https://github.com/BigstickCarpet/swagger-server#swagger-server) with a deprecation notice and recommended alternatives.
