### ISSUE TITLE
Can't get it working. It returns "Error: 404 Error: /api/xxx Not Found"

### ISSUE THREAD

**Issue by apuchkov** [BigstickCarpet/swagger-server#4]
I'm trying swagger-server for the first time and can't get it running.

Here's my code:

**server.js**

```javascript
'use strict';

process.env.DEBUG = 'swagger:*';

var swaggerServer = require('swagger-server');
var app = swaggerServer('banks-api.json');

// Start listening on port 8000
app.listen(8000, function() {
  console.log('The Swagger Mock Banks API is now running at http://localhost:8000');
});
```

**banks-api.json**

```javascript
{
  "swagger": "2.0",
  "info": {
    "version": "v1",
    "title": "banks api"
  },
  "host": "localhost:64123",
  "schemes": [
    "http"
  ],
  "paths": {
    "/api/banks": {
      "get": {
        "tags": [
          "Bank"
        ],
        "operationId": "Bank_GetBanks",
        "consumes": [],
        "produces": [
          "application/json",
          "text/json",
          "application/xml",
          "text/xml"
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/BankViewModel"
              }
            }
          }
        },
        "deprecated": false
      }
    },
    "/api/banks/{bankId}": {
      "get": {
        "tags": [
          "Bank"
        ],
        "operationId": "Bank_GetBank",
        "consumes": [],
        "produces": [
          "application/json",
          "text/json",
          "application/xml",
          "text/xml"
        ],
        "parameters": [
          {
            "name": "bankId",
            "in": "path",
            "required": true,
            "type": "integer",
            "format": "int32"
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/BankViewModel"
            }
          }
        },
        "deprecated": false
      }
    }
  },
  "definitions": {
    "BankViewModel": {
      "type": "object",
      "properties": {
        "BankId": {
          "format": "int32",
          "type": "integer"
        },
        "Name": {
          "type": "string"
        }
      }
    }
  }
}
```

It seems to start successfully...

```
C:\projects\swagger-server>node server.js
  swagger:server Parsing Swagger file "banks-api.json" +0ms
  swagger:parser Resolving path "banks-api.json", relative to "c:\projects\swagger-server\" +5ms
  swagger:parser     Resolved to c:\projects\swagger-server\banks-api.json +2ms
  swagger:parser Swagger base directory: c:\projects\swagger-server\ +0ms
  swagger:parser Reading file "c:\projects\swagger-server\banks-api.json" +1ms
  swagger:parser Parsing YAML file "c:\projects\swagger-server\banks-api.json" +2ms
  swagger:parser     Parsed successfully +2ms
  swagger:parser Resolving $ref pointers in c:\projects\swagger-server\banks-api.json +1ms
  swagger:parser Resolved /paths//api/banks/{bankId}/get/responses/200/schema/$ref => #/definitions/BankViewModel +1ms
  swagger:parser Resolved /paths//api/banks/get/responses/200/schema/items/$ref => #/definitions/BankViewModel +1ms
  swagger:parser Validating "c:\projects\swagger-server\banks-api.json" against the Swagger schema +3ms
  swagger:parser     Validated successfully +19ms
  swagger:server Done parsing Swagger file "banks-api.json" +3ms
  swagger:server Starting HTTP server +2ms
The Swagger Mock Banks API is now running at http://localhost:8000
```

but then when I access http://localhost:8000/api/banks/1 it fails...
```
  swagger:middleware GET /api/banks/1 matches Swagger path /api/banks/{bankId} +53s
  swagger:middleware Parsing 1 request parameters... +5ms
  swagger:middleware     Parsing the "bankId" path parameter +1ms
  swagger:middleware Validating Accept header (text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8) +2ms
  swagger:middleware Validating Content-Length header (NaN) +1ms
  swagger:middleware Using 200 response for GET /api/banks/1 +2ms
  swagger:middleware Running the queryResource mock +1ms
  swagger:middleware ERROR! 404 - GET /api/banks/1 does not exist +2ms
Error: 404 Error: /api/banks/1 Not Found
    at Object.module.exports.newError (C:\projects\swagger-server\node_modules\swagger-server\node_modules\swagger-express-middleware\lib\helpers\util.js:73:18)
    at C:\projects\swagger-server\node_modules\swagger-server\node_modules\swagger-express-middleware\lib\mock\query-resource.js:33:20
    at doCallback (C:\projects\swagger-server\node_modules\swagger-server\node_modules\swagger-express-middleware\lib\data-store\index.js:302:5)
    at C:\projects\swagger-server\node_modules\swagger-server\node_modules\swagger-express-middleware\lib\data-store\index.js:48:7
    at Object.<anonymous> (C:\projects\swagger-server\node_modules\swagger-server\node_modules\swagger-express-middleware\lib\data-store\index.js:289:5)
    at Object.immediate._onImmediate (timers.js:372:16)
    at processImmediate [as _immediateCallback] (timers.js:354:15)
```

Am I doing something wrong?

**Comment by BigstickCarpet** [comment]
You have to create a REST resource at `/api/banks/1` first; otherwise you'll get a 404, since the resource does not exist.

You can programmatically create a REST resource and pre-load it when your server starts, like this:

```javascript
var swaggerServer = require('swagger-server');
var app = swaggerServer('banks-api.json');

// Create Bank #1
var myBank = new swaggerServer.Resource('/api/banks', 1, {BankId: 1, Name: 'My Bank'});
app.dataStore.save(myBank);

// Start listening on port 8000
app.listen(8000, function() { ... }
```

Or you can add a POST operation to your `/api/banks` path, or a PUT operation to your `/api/banks/{bankId}` path.   Then use a tool like [Postman](https://www.getpostman.com/) to add banks at runtime.

```json
  "paths": {
    "/api/banks": {
      "post": {
        "description": "Create a new bank",
        "consumes": ["application/json"],
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/BankViewModel"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "Bank created successfully",
            "headers": {
              "Location": {
                "type": "string"
              }
            }
          }
        }
      },
```

I suggest that you [read the walkthroughs](https://github.com/BigstickCarpet/swagger-server/blob/master/samples/docs/running.md) for lots more information

**Comment by apuchkov** [comment]
Thanks for a quick reply.

I had impression though that swagger-server will generate mocks automatically:

> **Intelligent Mocks**
> Swagger Server automatically provides mock implementations for every operation in your API  definition, complete with data persistence. So you can have a fully-functional mock API with *zero code*.

**Comment by apuchkov** [comment]
I see now that records have to be created via API or programmatically. I just got impression that swagger-server will generate and return mocked entities by itself based on provided swagger spec. 

Thanks for a quick reply.

**Comment by BigstickCarpet** [comment]
Sorry for the confusion.  Swagger Server doesn't generate mock data.  It provides mock implementations for the REST operations that you define in your Swagger API.

If your API defines POST, PUT, or PATCH operations for a given path, then you can use those operations to add data, and then when you do GET request, you'll see the data you added.   Or, if you don't want your API to include writable operations, then you'll need to load data programmatically, via the [`DataStore`](https://github.com/BigstickCarpet/swagger-express-middleware/blob/master/docs/exports/DataStore.md) and [`Resource`](https://github.com/BigstickCarpet/swagger-express-middleware/blob/master/docs/exports/Resource.md) APIs.

**Comment by noecobian** [comment]
I'm getting something similar, but I am creating the resources, using similar code to the one sugested

>var myBank = new swaggerServer.Resource('/api/banks', 1, {BankId: 1, Name: 'My Bank'});
>app.dataStore.save(myBank);
>var myBank = new swaggerServer.Resource('/api/banks', 2, {BankId: 2, Name: 'My Other Bank'});
>app.dataStore.save(myBank);

 receiving a 404 not found

so I deleted the second parameter, 

>var myBank = new swaggerServer.Resource('/api/banks', {BankId: 1, Name: 'My Bank'});
>app.dataStore.save(myBank);
>var myBank = new swaggerServer.Resource('/api/banks', {BankId: 2, Name: 'My Other Bank'});
>app.dataStore.save(myBank);

and do receive a response back, but only receive one object back, seems to be overwriting. How can I receive both my objects back preloading my objects?

**Comment by BigstickCarpet** [comment]
@noecobian - Please refer to the docs for the [`Resource` class](https://github.com/BigstickCarpet/swagger-express-middleware/blob/master/docs/exports/Resource.md)?  It explains the difference between the two-parameter and three-parameter constructors.

In your first example, you are creating _two_ REST resources.  One at `/api/banks/1` and one at `/api/banks/2`.  In your second example, you are creating _one_ REST resource at `/api/banks` and then immediately overwriting it with a different resource at the same URL.
