### ISSUE TITLE
Add support to listen on a named pipes as well as ports 

### ISSUE THREAD

**Issue by supernik** [BigstickCarpet/swagger-server#5]
This project is great and we a4 using it to construct a mock server for our system.     The issue is that we are MS Azure based and WebApps that support Node only support named pipes.

I have hacked the code to test if it would on Azure and it worked! If you're interested I can work on this to provide a solution

**Comment by BigstickCarpet** [comment]
Cool!  I have no experience at all with MS Azure, so I'd definitely appreciate your help.  How significant are the changes that need to be made?

**Comment by supernik** [comment]
The changes I made were in the application.js file in app.listen.  The issue is that the code is checking for ports as numbers in that function.

The other implication is that you would have to ignore the host entry in the spec file for this to work too.

**Comment by BigstickCarpet** [comment]
Oh, ok.  Replacing `_.isNumber(port)` with `_.isUndefined(port)` is a pretty easy change.   But ignoring the host entry in the Swagger spec is a bit harder to solve elegantly.   We could just leave that logic as-is, and it'll work fine on Azure as long as the spec doesn't include a port number (which most don't).  What do you think?

**Comment by BigstickCarpet** [comment]
Thanks for submitting a pull request for this!  It has been merged and is included in version `1.0.0-alpha.8`
