### ISSUE TITLE
Started server on port 9091, but cannot get a response

### ISSUE THREAD

**Issue by SteveNewhouse** [BigstickCarpet/swagger-server#9]
Hello--

New to swagger-server.  Just trying to get it going with the following setup:

```javascript
process.env.DEBUG = 'swagger:*';

var swaggerServer = require('swagger-server');
var app = swaggerServer('../specs/worker.yaml');

// GET /users
app.get('/users', function(req, res, next) {
    res.send(myListOfUsers);
});

// Start listening on port 9091
app.listen(9091, function() {
  console.log('Your REST API is now running at http://localhost:9091');
});
```

It parses the spec with no errors, but when I load localhost:9091 I get "Cannot GET /assignments" which should be a valid endpoint.

**Comment by BigstickCarpet** [comment]
Can you post `worker.yaml`?   

Make sure you have a `GET` operation defined for `/assignments`.  Also, if you have a `basePath` defined, remember to include it (e.g. `/api/v1/assignments`)

**Comment by SteveNewhouse** [comment]
It was basePath... thank you!

**Comment by BigstickCarpet** [comment]
Awesome.  Glad you got it working!
